"""Review/QA Agent — audits other agents' output for quality and brand consistency."""

import sys
import json
import asyncio
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from agent_base import BaseAgent, AgentEvent
from tools.file_tools import list_outputs, save_template


REVIEW_PROMPT = """You are a quality assurance reviewer for a digital products business.
Review the following content that was generated by an AI agent.

File type: {file_type}
Content:
---
{content}
---

Score this output on a 0-100 scale across these criteria and return a JSON object:
- "overall_score": Weighted average score (0-100)
- "scores": Object with:
  - "completeness": Is it complete and well-structured? (0-100)
  - "quality": Is the writing/code quality professional? (0-100)
  - "brand_consistency": Does it match a professional finance brand? (0-100)
  - "accuracy": Are claims, numbers, and formatting correct? (0-100)
  - "actionability": Could this be used as-is or near as-is? (0-100)
- "issues": Array of specific issues found (empty if none)
- "strengths": Array of things done well
- "verdict": "pass" | "needs_revision" | "reject"
- "revision_notes": If needs_revision, specific instructions for improvement (else null)
- "summary": 1-2 sentence quality summary

Be strict but fair. A score of 70+ is a pass. Under 50 is reject.
Return ONLY valid JSON."""


class ReviewAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            agent_id="review-001",
            name="Review/QA Agent",
            description="Quality audits on agent output",
            color="#14b8a6",
        )
        self.tick_interval = 180
        self.pipeline_db = None
        self.reviewed_files = set()  # track already-reviewed filenames

    async def tick(self) -> AgentEvent:
        # Get recent output files
        files = await asyncio.to_thread(list_outputs, "printables")

        if not files:
            self.current_task = None
            return self.emit("waiting", "No output files to review")

        # Find one we haven't reviewed yet
        target = None
        for f in files:
            if f["filename"] not in self.reviewed_files:
                target = f
                break

        if not target:
            # Reset and re-review (outputs keep growing)
            if len(files) > len(self.reviewed_files):
                self.reviewed_files.clear()
                target = files[0]
            else:
                self.current_task = None
                return self.emit("waiting", "All recent outputs reviewed")

        filename = target["filename"]
        self.current_task = {
            "type": "qa-review",
            "description": f"Reviewing {filename}",
        }

        self.emit("reviewing", f"Auditing {filename}")

        try:
            # Read the file content (cap at 3000 chars to stay within LLM limits)
            filepath = Path(target["path"])
            content = await asyncio.to_thread(
                filepath.read_text, "utf-8"
            )
            content_preview = content[:3000]
            if len(content) > 3000:
                content_preview += "\n\n[... truncated for review ...]"

            file_type = "HTML" if filename.endswith(".html") else "JSON" if filename.endswith(".json") else "text"

            prompt = REVIEW_PROMPT.format(
                file_type=file_type,
                content=content_preview,
            )
            system = (
                "You are a strict but fair QA reviewer for a digital products business. "
                "You evaluate AI-generated content for professional quality. "
                "Output only valid JSON."
            )

            result = await self.llm.generate(prompt, system=system, complexity="low")

            if "```json" in result:
                result = result.split("```json")[1].split("```")[0].strip()
            elif "```" in result:
                result = result.split("```")[1].split("```")[0].strip()

            try:
                review = json.loads(result)
            except json.JSONDecodeError:
                self.current_task = None
                return self.emit("skipped", f"Invalid review JSON for {filename}")

            score = review.get("overall_score", 0)
            verdict = review.get("verdict", "unknown")

            # Save the review report
            review["reviewed_file"] = filename
            review["reviewed_at"] = target.get("modified", "")
            save_template(
                json.dumps(review, indent=2),
                f"review-{filename.rsplit('.', 1)[0]}",
                fmt="json"
            )

            self.reviewed_files.add(filename)
            self.tasks_completed += 1
            self.current_task = None

            verdict_emoji = "PASS" if verdict == "pass" else "REVISE" if verdict == "needs_revision" else "REJECT"
            return self.emit(
                "completed",
                f"Reviewed '{filename}': {score}/100 [{verdict_emoji}]"
            )

        except Exception as e:
            self.current_task = None
            return self.emit("error", f"Review failed for {filename}: {e}")

    def get_tools(self) -> list[dict]:
        return []
