"""Review/QA Agent — audits other agents' output for quality and brand consistency.

Previously scoped to only `output/printables/`. Now rotates through every
output subdirectory the farm writes to, so all 21 agents' outputs get reviewed.
"""

import sys
import json
import asyncio
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from agent_base import BaseAgent, AgentEvent
from tools.file_tools import list_outputs, ensure_output_dir, OUTPUT_DIR


# All output subdirectories this farm uses. New agents should add themselves here.
REVIEW_SUBDIRS = [
    "printables",
    "content-scripts",
    "freelance-gigs",
    "gumroad-listings",
    "image-prompts",
    "videos",
]


REVIEW_PROMPT = """You are a quality assurance reviewer for a digital products business.
Review the following content that was generated by an AI agent.

Source agent area: {subdir}
File type: {file_type}
Content:
---
{content}
---

Score this output on a 0-100 scale across these criteria and return a JSON object:
- "overall_score": Weighted average score (0-100)
- "scores": Object with:
  - "completeness": Is it complete and well-structured? (0-100)
  - "quality": Is the writing/code quality professional? (0-100)
  - "brand_consistency": Does it match a professional finance brand? (0-100)
  - "accuracy": Are claims, numbers, and formatting correct? (0-100)
  - "actionability": Could this be used as-is or near as-is? (0-100)
- "issues": Array of specific issues found (empty if none)
- "strengths": Array of things done well
- "verdict": "pass" | "needs_revision" | "reject"
- "revision_notes": If needs_revision, specific instructions for improvement (else null)
- "summary": 1-2 sentence quality summary

Be strict but fair. A score of 70+ is a pass. Under 50 is reject.
Return ONLY valid JSON."""


def _detect_file_type(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith((".html", ".htm")):
        return "HTML"
    if lower.endswith(".json"):
        return "JSON"
    if lower.endswith((".tsx", ".ts")):
        return "TypeScript/React"
    if lower.endswith(".svg"):
        return "SVG"
    if lower.endswith(".md"):
        return "Markdown"
    return "text"


class ReviewAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            agent_id="review-001",
            name="Review/QA Agent",
            description="Quality audits on every agent's output",
            color="#14b8a6",
        )
        self.tick_interval = 180
        self.pipeline_db = None
        # Track reviewed filenames per-subdir so each area gets fair rotation
        self.reviewed_files: dict[str, set[str]] = {sub: set() for sub in REVIEW_SUBDIRS}
        self._subdir_cursor = 0  # rotates which subdir we review next

    async def tick(self) -> AgentEvent:
        # Find the next subdir with something to review, starting from cursor
        target_file = None
        target_subdir = None

        attempts = 0
        while attempts < len(REVIEW_SUBDIRS):
            subdir = REVIEW_SUBDIRS[self._subdir_cursor % len(REVIEW_SUBDIRS)]
            self._subdir_cursor += 1
            attempts += 1

            files = await asyncio.to_thread(self._collect_files, subdir)
            if not files:
                continue

            seen = self.reviewed_files.setdefault(subdir, set())
            unreviewed = [f for f in files if f["filename"] not in seen]

            if unreviewed:
                target_file = unreviewed[0]
                target_subdir = subdir
                break

            # All files in this subdir already reviewed — if the file list has grown,
            # clear and re-audit the newest one (catches changed content on next pass)
            if len(files) > len(seen):
                seen.clear()
                target_file = files[0]
                target_subdir = subdir
                break

        if not target_file:
            self.current_task = None
            return self.emit("waiting", "All recent outputs reviewed across all agent areas")

        filename = target_file["filename"]
        self.current_task = {
            "type": "qa-review",
            "description": f"Reviewing {target_subdir}/{filename}",
        }
        self.emit("reviewing", f"Auditing {target_subdir}/{filename}")

        try:
            filepath = Path(target_file["path"])
            content = await asyncio.to_thread(filepath.read_text, "utf-8")
            content_preview = content[:3000]
            if len(content) > 3000:
                content_preview += "\n\n[... truncated for review ...]"

            file_type = _detect_file_type(filename)

            prompt = REVIEW_PROMPT.format(
                subdir=target_subdir,
                file_type=file_type,
                content=content_preview,
            )
            system = (
                "You are a strict but fair QA reviewer for a digital products business. "
                "You evaluate AI-generated content for professional quality. "
                "Output only valid JSON."
            )

            result = await self.llm.generate(prompt, system=system, complexity="low")

            if "```json" in result:
                result = result.split("```json")[1].split("```")[0].strip()
            elif "```" in result:
                result = result.split("```")[1].split("```")[0].strip()

            try:
                review = json.loads(result)
            except json.JSONDecodeError:
                self.reviewed_files[target_subdir].add(filename)  # skip this file going forward
                self.current_task = None
                return self.emit("skipped", f"Invalid review JSON for {target_subdir}/{filename}")

            score = review.get("overall_score", 0)
            verdict = review.get("verdict", "unknown")

            # Save the review report into a dedicated reviews folder, organized by source subdir
            review["reviewed_file"] = filename
            review["reviewed_subdir"] = target_subdir
            review["reviewed_at"] = target_file.get("modified", "")

            reviews_dir = ensure_output_dir(f"reviews/{target_subdir}")
            review_filename = f"review-{filename.rsplit('.', 1)[0]}.json"
            (reviews_dir / review_filename).write_text(
                json.dumps(review, indent=2), encoding="utf-8"
            )

            self.reviewed_files[target_subdir].add(filename)
            self.tasks_completed += 1
            self.current_task = None

            verdict_tag = (
                "PASS" if verdict == "pass"
                else "REVISE" if verdict == "needs_revision"
                else "REJECT"
            )
            return self.emit(
                "completed",
                f"Reviewed {target_subdir}/{filename}: {score}/100 [{verdict_tag}]"
            )

        except Exception as e:
            self.current_task = None
            return self.emit("error", f"Review failed for {target_subdir}/{filename}: {e}")

    @staticmethod
    def _collect_files(subdir: str) -> list[dict]:
        """Fetch output files for a subdir, tolerating nested project dirs (e.g. videos/<slug>/)."""
        files = list_outputs(subdir)
        if files:
            return files

        # Some agents (Video Producer) create nested project folders rather than flat files.
        # Fall back to scanning one level deep for primary artifacts.
        root = (OUTPUT_DIR / subdir).resolve()
        if not str(root).startswith(str(OUTPUT_DIR.resolve())):
            return []
        if not root.exists():
            return []

        nested: list[dict] = []
        for project in sorted(root.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True):
            if not project.is_dir():
                continue
            # Look for the primary artifact inside each project dir
            candidates = [
                project / "src" / "MyVideo.tsx",
                project / "README.md",
            ]
            for cand in candidates:
                if cand.exists():
                    stat = cand.stat()
                    nested.append({
                        "filename": f"{project.name}/{cand.relative_to(project).as_posix()}",
                        "path": str(cand),
                        "size_bytes": stat.st_size,
                        "modified": stat.st_mtime,
                    })
                    break
        return nested

    def get_tools(self) -> list[dict]:
        return []
