"""Template generation tools — prompts and post-processing for printable designs."""

TEMPLATE_TYPES = {
    "trading-journal": {
        "title": "Trading Journal",
        "description": "Daily trading log with entry/exit tracking, P&L, and notes",
        "sections": ["Date", "Instrument", "Entry Price", "Exit Price", "Position Size",
                      "P&L", "Strategy Used", "Emotion Check", "Lessons Learned"],
    },
    "budget-tracker": {
        "title": "Monthly Budget Tracker",
        "description": "Income vs expenses breakdown with category tracking",
        "sections": ["Income Sources", "Fixed Expenses", "Variable Expenses",
                      "Savings Goals", "Debt Payments", "Monthly Summary"],
    },
    "expense-log": {
        "title": "Daily Expense Log",
        "description": "Day-by-day expense tracking with categories",
        "sections": ["Date", "Category", "Description", "Amount", "Payment Method",
                      "Running Total", "Weekly Summary"],
    },
    "portfolio-tracker": {
        "title": "Investment Portfolio Tracker",
        "description": "Track holdings, allocations, and performance across accounts",
        "sections": ["Asset Name", "Ticker", "Shares", "Cost Basis", "Current Price",
                      "Gain/Loss", "Allocation %", "Account", "Sector"],
    },
    "net-worth": {
        "title": "Net Worth Statement",
        "description": "Assets vs liabilities snapshot with monthly tracking",
        "sections": ["Cash & Savings", "Investment Accounts", "Real Estate",
                      "Other Assets", "Credit Cards", "Loans", "Net Worth Total"],
    },
    "goal-planner": {
        "title": "Financial Goal Planner",
        "description": "Set and track financial milestones with timelines",
        "sections": ["Goal Name", "Target Amount", "Current Amount", "Monthly Contribution",
                      "Target Date", "Progress Bar", "Action Items"],
    },
    "debt-payoff": {
        "title": "Debt Payoff Tracker",
        "description": "Track debt balances and payoff progress",
        "sections": ["Debt Name", "Original Balance", "Current Balance", "Interest Rate",
                      "Minimum Payment", "Extra Payment", "Payoff Date", "Total Interest"],
    },
    "income-tracker": {
        "title": "Income & Revenue Tracker",
        "description": "Multi-stream income tracking with monthly/yearly views",
        "sections": ["Income Source", "Type", "Amount", "Date Received",
                      "Monthly Total", "YTD Total", "Growth %"],
    },
    "habit-tracker": {
        "title": "Financial Habits Tracker",
        "description": "Daily habits that build wealth — track consistency",
        "sections": ["Habit", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun",
                      "Streak", "Monthly Score"],
    },
    "monthly-review": {
        "title": "Monthly Financial Review",
        "description": "End-of-month financial health check and reflection",
        "sections": ["Net Income", "Savings Rate", "Top 3 Expenses", "Investments Added",
                      "Goals Progress", "Wins", "Improvements", "Next Month Focus"],
    },
}


def get_template_prompt(template_type: str) -> str:
    """Build the LLM prompt for generating a printable template."""
    tmpl = TEMPLATE_TYPES.get(template_type)
    if not tmpl:
        tmpl = TEMPLATE_TYPES["trading-journal"]

    sections_list = "\n".join(f"  - {s}" for s in tmpl["sections"])

    return f"""Create a beautiful, print-ready HTML template for a "{tmpl['title']}".

Description: {tmpl['description']}

Required sections/fields:
{sections_list}

Design requirements:
- Clean, minimal aesthetic with good use of whitespace
- Use a professional color scheme (dark headers, light backgrounds, subtle accent colors)
- Include a decorative header with the template title
- Use CSS Grid or Flexbox for layout
- Tables should have alternating row colors
- Include placeholder text showing example data
- Size: US Letter (8.5" x 11") portrait orientation
- Add @media print styles for clean printing
- Use web-safe fonts (Georgia for headings, system-ui for body)
- Include subtle borders and divider lines
- Add a small footer with "Generated by Agent Farm"

Return ONLY the complete HTML document (<!DOCTYPE html> to </html>).
Do not include any explanation, just the HTML code."""


def get_variation_prompt(template_type: str, style: str = "modern") -> str:
    """Build a prompt for a style variation of a template."""
    tmpl = TEMPLATE_TYPES.get(template_type, TEMPLATE_TYPES["trading-journal"])

    styles = {
        "modern": "Sleek, minimal, lots of whitespace, thin borders, monochrome with one accent color",
        "classic": "Traditional ledger style, serif fonts, double-line borders, cream/ivory tones",
        "bold": "Strong colors, thick borders, large headers, high contrast, statement piece",
        "pastel": "Soft pastel colors, rounded corners, gentle gradients, friendly and approachable",
    }

    style_desc = styles.get(style, styles["modern"])
    base_prompt = get_template_prompt(template_type)

    return base_prompt.replace(
        "Design requirements:",
        f"Style: {style} — {style_desc}\n\nDesign requirements:"
    )


GENERATE_TEMPLATE_SCHEMA = {
    "name": "generate_template",
    "description": "Generate a printable financial template using AI",
    "input_schema": {
        "type": "object",
        "properties": {
            "template_type": {
                "type": "string",
                "enum": list(TEMPLATE_TYPES.keys()),
                "description": "The type of financial template to generate",
            },
            "style": {
                "type": "string",
                "enum": ["modern", "classic", "bold", "pastel"],
                "default": "modern",
            },
        },
        "required": ["template_type"],
    },
}
